apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  platform: azure
  generationRules:
    - resourceTypes:
        - azure_network_security_groups
      matchRules:
        - type: pattern
          pattern: ".+"
          properties: [name]
          mode: substring
      slxs:
        - baseName: azure-network-security-integrity
          qualifiers: ["resource", "resource_group"]
          baseTemplateName: azure-network-security-integrity
          levelOfDetail: basic
          outputItems:
            - type: slx
            - type: sli
            - type: runbook
              templateName: azure-network-security-integrity-taskset.yaml
            - type: workflow
