apiVersion: runwhen.com/v1
kind: Workflow
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  description: Automated integrity workflow for azure network security
  location: {{default_location}}
  steps:
    - name: check-integrity
      runbook:
        name: {{slx_name}}-runbook
      triggers:
        - type: sli
          sliName: {{slx_name}}-sli
          operator: <
          threshold: 1
