apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  description: Integrity monitoring for azure network security
  sli:
    name: {{slx_name}}-sli
  runbook:
    name: {{slx_name}}-runbook
